#Configuração de Limites do TitamMods
[limits]
	#Se true, operadores (OP) ignoram os limites.
	op_bypass = true
	#Lista de limites de blocos (TileEntities).
	#Formato: 'modid:block_id|limite'
	#Exemplo: Limitar Funis a 8 por chunk.
	block_limits = ["minecraft:hopper|8", "mekanism:digital_miner|1"]
	#Lista de limites de entidades (Mobs/Vehicles).
	#Formato: 'modid:entity_id|limite'
	entity_limits = ["minecraft:villager|20", "minecraft:cow|30"]
