#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Mar 08 13:24:40 CET 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
